# TensorFlow 2.0模式
#### Eager Execution(动态图执行机制)

### 版本号

In [1]:
import tensorflow as tf

tf.__version__

'2.0.0'

### 定义节点

In [2]:
node1 = tf.constant([[3.0, 1.5], [2.5, 6.0]], tf.float32)
node2 = tf.constant([[4.0, 1.0], [5.0, 2.5]], tf.float32)
node3 = tf.add(node1, node2)

### 查看节点信息

In [3]:
node1

<tf.Tensor: id=0, shape=(2, 2), dtype=float32, numpy=
array([[3. , 1.5],
       [2.5, 6. ]], dtype=float32)>

In [4]:
node2

<tf.Tensor: id=1, shape=(2, 2), dtype=float32, numpy=
array([[4. , 1. ],
       [5. , 2.5]], dtype=float32)>

In [5]:
node3

<tf.Tensor: id=2, shape=(2, 2), dtype=float32, numpy=
array([[7. , 2.5],
       [7.5, 8.5]], dtype=float32)>

### Tensor 转 Numpy

In [6]:
print('Class:', type(node3.numpy()),
      '\nValue:\n', node3.numpy(),
      '\nShape:', node3.shape,
      '\nDtype:', node3.dtype)

Class: <class 'numpy.ndarray'> 
Value:
 [[7.  2.5]
 [7.5 8.5]] 
Shape: (2, 2) 
Dtype: <dtype: 'float32'>


### 张量形状
shape 与 get_shape()具有相同的作用

In [7]:
scalar = tf.constant(100)
vector = tf.constant([1, 2, 3, 4, 5])
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
cube_matrix = tf.constant([[[1], [2], [3]], [[4], [5], [6]], [[7], [8], [9]]])

print('scalar shape', ' ' * 3, ':', scalar.shape)
print('vector shape', ' ' * 3, ':',  vector.shape)
print('matrix shape', ' ' * 3, ':',  matrix.shape)
print('cube_matrix shape:', cube_matrix.get_shape())

scalar shape     : ()
vector shape     : (5,)
matrix shape     : (2, 3)
cube_matrix shape: (3, 3, 1)


### 通过下标获取值

In [8]:
print('A value in cube_matrix[1, 2, 0]:', cube_matrix.numpy()[1, 2, 0])

A value in cube_matrix[1, 2, 0]: 6


### TensorFlow 严控数据类型
tf.constant(  
&ensp;&ensp;&ensp;&ensp;value,  
&ensp;&ensp;&ensp;&ensp;dtype=None,  
&ensp;&ensp;&ensp;&ensp;shape=None,  
&ensp;&ensp;&ensp;&ensp;name='Const'  
&ensp;&ensp;&ensp;&ensp;)

In [9]:
node_a = tf.constant([1, 2], dtype=tf.int32)
node_b = tf.constant([3.0, 4.0], dtype=tf.float32)

try:
    node_result = tf.add(node_a, node_b)
except:
    print('INFO:cannot compute Add as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:Add]')
    print('INFO:you\'d, transform the dtype')
finally:
    node_cast_a = tf.cast(node_a, tf.float32)
    node_result = tf.add(node_cast_a, node_b)
    print('Result:', node_result,
         '\nValue:', node_result.numpy())

INFO:cannot compute Add as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:Add]
INFO:you'd, transform the dtype
Result: tf.Tensor([4. 6.], shape=(2,), dtype=float32) 
Value: [4. 6.]


### TensorFlow 变量
tf.Variable(  
&ensp;&ensp;&ensp;&ensp;initial_value,  
&ensp;&ensp;&ensp;&ensp;dtype=None,  
&ensp;&ensp;&ensp;&ensp;shape=None,  
&ensp;&ensp;&ensp;&ensp;trainable=True,  
&ensp;&ensp;&ensp;&ensp;name='Variable',  
&ensp;&ensp;&ensp;&ensp;)  
TensorFlow 变量一般用于机器迭代自动修改值，但人工也可以主动进行修改，变量创建必须指定初始值，像定义常量一样，变量的类型由初始值确定，如下

In [10]:
variable_1 = tf.Variable([1, 2])
variable_2 = tf.Variable([3, 4], tf.float32)

variable_1, variable_2

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>)

可以使用张量作为初始值

In [11]:
variable_3 = tf.constant(1, dtype=tf.float32)
variable_4 = tf.Variable(variable_3)

variable_3, variable_4

(<tf.Tensor: id=28, shape=(), dtype=float32, numpy=1.0>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>)

特殊情况需要人工更新，可用变量赋值语句 assign() 实现，比如在断点续训例子中，将会用到这个功能，TensorFlow 2.x提供 assign_add()、assign_sub()实现变量加减

In [12]:
variable_5 = tf.Variable(5)
variable_6 = tf.Variable(5)
variable_7 = tf.Variable(7)

variable_5.assign(variable_5 + 1)
variable_6.assign_add(1)
variable_7.assign_sub(1)
print('variable_5 + 1:', variable_5,
      '\nvariable_6 + 1:', variable_6,
      '\nvariable_7 + 1:', variable_7)

variable_5 + 1: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6> 
variable_6 + 1: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6> 
variable_7 + 1: <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>


# TensorFlow 2.0 实现 1.x模式
#### Graph Execution(静态图执行机制)
`compat` 中文意思为`兼容`，v1指 `tensorflow 1.x`，`tensorflow.compat.v1` 含义则是兼容 `tensorflow 1.x` 的接口，实际上，`tensorflow 2.x` 将 `tensorflow 1.x` 全部接口写入了 `tensorflow.compat.v1`

In [13]:
import tensorflow.compat.v1 as tf

tf.disable_eager_execution()

In [14]:
node1 = tf.constant(3.0, tf.float32, name='node1')
node2 = tf.constant(3.0, tf.float32, name='node2')
node3 = tf.add(node1, node2)

node3

<tf.Tensor 'Add:0' shape=() dtype=float32>

**tf.Session()创建一个会话，当上下文管理器退出时会话关闭和资源释放自动完成**  
**tf.Session().as_default()创建一个默认会话，当上下文管理器退出时会话没有关闭，还可以通过调用会话进行run()和eval()操作**  
**在管理器内部直接使用 eval()，在管理器外部[未启用 sess.close()]，使用 eval(session=sess)**  
**在非 with 结构也需要使用 eval(session=sess)**

In [15]:
with tf.Session() as sess:
    print('node1 result:', sess.run(node1))
    print('node2 result:', sess.run(node2))
    print('node3 result:', sess.run(node3))
    print('node3 eval:', node3.eval())

try:
    print('Even out with session, the node3 value is:', node3.eval(session=sess))
except RuntimeError:
    print('RuntimeError:attempted to use a closed Session.')
finally:
    print('session done')

node1 result: 3.0
node2 result: 3.0
node3 result: 6.0
node3 eval: 6.0
RuntimeError:attempted to use a closed Session.
session done


In [16]:
with tf.Session().as_default() as sess:
    print('node1 result:', sess.run(node1))
    print('node2 result:', sess.run(node2))
    print('node3 result:', sess.run(node3))
    print('node3 eval:', node3.eval())

try:
    print('Even out with session, the node3 value is:', node3.eval(session=sess))
except RuntimeError:
    print('RuntimeError:attempted to use a closed Session.')
finally:
    print('session done')
    
sess.close()
try:
    print('Closed session, the node3 value is:', node3.eval(session=sess))
except RuntimeError:
    print('RuntimeError:attempted to use a closed Session.')
finally:
    print('Session done, cause I use sess.close()')

node1 result: 3.0
node2 result: 3.0
node3 result: 6.0
node3 eval: 6.0
Even out with session, the node3 value is: 6.0
session done
RuntimeError:attempted to use a closed Session.
Session done, cause I use sess.close()


In [17]:
sess = tf.Session()
try:
    print('node3.eval() value', node3.eval())
except ValueError:
    print(('Cannot evaluate tensor using `eval()`: No default session is registered.'
            'Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`'))
finally:
    print('node3.eval() value:', node3.eval(session=sess))

Cannot evaluate tensor using `eval()`: No default session is registered.Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`
node3.eval() value: 6.0


**在交互式环境下，`Python` 脚本或者 `Jupyter` 编辑器下，通过设置默认会话来获取张量的取值更加方便**  
**`tf.InteractiveSession` 这个函数会自动将生成的会话注册为默认会话**

In [18]:
sess = tf.InteractiveSession()

print('node3 InteractiveSession value:', node3.eval())
sess.close()

node3 InteractiveSession value: 6.0


#### TensorFlow 1.x Variable
变量 Variable 在 Tensorflow 中需进行初始化操作：  
name_variable = tf.Variable(value, name)  
init_op = name_variable.initializer()&ensp;&ensp;&ensp;&ensp;个别变量初始化  
init_op = tf.global_variables_initializer() 所有变量初始化

In [19]:
node1 = tf.Variable(3.0, tf.float32, name='node1')
node2 = tf.Variable(3.0, tf.float32, name='node2')
result = tf.add(node1, node2)

try:
    sess = tf.Session()
    print('sess.run(result) value:', sess.run(result))
except:
    init = tf.global_variables_initializer()
    sess = tf.Session()
    sess.run(init)
    print('sess.run(result) value:', sess.run(result))
finally:
    print('Variables must be initialized')
    sess.close()

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
sess.run(result) value: 6.0
Variables must be initialized


#### 变量复制案例  
tf.assign(variable_to_be_updated, new_value)，将 new_value 的值赋给 variable_to_be_updated

In [20]:
import os


tf.reset_default_graph()

value = tf.Variable(0, name='value')
one = tf.constant(1)
new_value = tf.add(value, one)
update_value = tf.assign(value, new_value)

init = tf.global_variables_initializer()
print('result:', end='')

with tf.Session() as sess:
    sess.run(init)
    for _ in range(10):
        sess.run(update_value)
        print(sess.run(value),end=' ')

logdir='TensorFlow_2.x_tutorial_logs'

if not os.path.exists(logdir):
    os.mkdir(logdir)

writer = tf.summary.FileWriter(logdir, tf.get_default_graph())
writer.close()

result:1 2 3 4 5 6 7 8 9 10 

### 思考题
#### TensorFlow 表示

In [21]:
sum_value = tf.Variable(0, name='sum_value')
num_value = tf.Variable(0, name='num_value')
one = tf.constant(1, name='one')

new_num_value = tf.add(num_value, one)
new_sum_value = tf.add(sum_value, num_value)
update_num_value = tf.assign(num_value, new_num_value)
update_sum_value = tf.assign(sum_value, new_sum_value)

init = tf.global_variables_initializer()
print('Result:1+2+3+4+5+6+7+8+9+10=', end='')
with tf.Session() as sess:
    sess.run(init)
    for i in range(10):
        sess.run(update_num_value)
        sess.run(update_sum_value)
    print(sess.run(sum_value))

Result:1+2+3+4+5+6+7+8+9+10=55


#### 基础 Python 表示

In [22]:
List = [i for i in range(1, 11)]
result_value = sum(List)
print('Result:1+2+3+4+5+6+7+8+9+10=%d' % result_value)

Result:1+2+3+4+5+6+7+8+9+10=55


### Tensorflow 基本运算
#### TensorFlow 数据喂入 feed 与占位符 placeholder
tf.placeholder(dtype, shape=None, name=None)  
未用到变量 `tf.Variable()` 可以不用初始化，注释 `sess.run(init)` 与 `init` 不会报错

In [23]:
a = tf.placeholder(tf.float32, name='a')
b = tf.placeholder(tf.float32, name='b')
c = tf.multiply(a, b, name='c')

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    result_sess_run = sess.run(c, feed_dict={a:5.20, b:13.14})
    result_eval = c.eval(feed_dict={a:5.20, b:13.14})
    print('sess.run caculate c value:', result_sess_run)
    print('c.eval caculate c value:', result_eval)

sess.run caculate c value: 68.328
c.eval caculate c value: 68.328


计算多个值

In [24]:
a = tf.placeholder(tf.float32, name='a')
b = tf.placeholder(tf.float32, name='b')
c = tf.multiply(a, b, name='c')
d = tf.subtract(a, b, name='d')

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    result = sess.run([c, d], feed_dict={a:[1, 2, 3], b:[4, 5, 6]})
    print('value:', result)
    print('first value:', result[0])
print('*******the another pattern*******')
with tf.Session() as sess:
    sess.run(init)
    result_1, result_2 = sess.run([c, d], feed_dict={a:[1, 2, 3], b:[4, 5, 6]})
    print('result_1:', result_1)
    print('result_2:', result_2)

value: [array([ 4., 10., 18.], dtype=float32), array([-3., -3., -3.], dtype=float32)]
first value: [ 4. 10. 18.]
*******the another pattern*******
result_1: [ 4. 10. 18.]
result_2: [-3. -3. -3.]


### Tensorboard 基本可视化操作

#### 基本函数介绍
#### tf.add_n(inputs, name=None)
A Tensor. Has the same type as inputs.Add all input tensors element wise.  
inputs: A list of at least 1 Tensor objects of the same type in: float32, float64, int64, int32, uint8, int16, int8, complex64, qint8, quint8, qint32. Must all be the same size and shape.  
name: A name for the operation (optional).  
Returns:A Tensor. Has the same type as inputs.
输入是一个列表，里面包含了一些 tensor(数据类型必须相同)，用于将列表中的 tensor 求和并返回
#### tf.random_uniform(  
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;shape,  
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;minval=0,  
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;maxval=None,  
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;dtype=tf.float32,  
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;seed=None,  
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;name=None  
#### &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;)  
从均匀分布中输出随机值。生成的值在该 [minval, maxval)范围内遵循均匀分布.下限 minval 包含在范围内,而上限 maxval 被排除在外。对于浮点数,默认范围是 [0, 1)。对于整数，至少 maxval 必须明确地指定。在整数情况下，随机整数稍有偏差，除非 maxval - minval 是 2 的精确幂。对于maxval - minval 的值，偏差很小，明显小于输出(2^32 或者 2^64)的范围。
参数：  
shape：一维整数张量或 Python 数组.输出张量的形状.  
minval：dtype 类型的 0-D 张量或 Python 值；生成的随机值范围的下限；默认为0.  
maxval：dtype 类型的 0-D 张量或 Python 值.要生成的随机值范围的上限.如果 dtype 是浮点,则默认为1 .  
dtype：输出的类型：float16、float32、float64、int32、orint64.  
seed：一个 Python 整数.用于为分布创建一个随机种子.查看 tf.set_random_seed 行为.  
name：操作的名称(可选).  
返回值：  
用于填充随机均匀值的指定形状的张量.  
可能引发的异常：  
ValueError：如果 dtype 是整数并且 maxval 没有被指定.  

In [25]:
tf.reset_default_graph()

logdir='./Tensorboard_basic_operation_logs'

if not os.path.exists(logdir):
    os.mkdir(logdir)

input1 = tf.constant([1.0, 2.0, 3.0], name='input1')

# input2
input2 = tf.Variable(tf.random_uniform([3]), name='input2')
output = tf.add_n([input1, input2], name='add')

writer = tf.summary.FileWriter(logdir, tf.get_default_graph())
writer.close()

上述 input2 采用 tf.random_uniform() 生成随机数，从输入参数可以表明其为一个具有三个元素的一维数组

In [26]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print('class:', type(sess.run(input2)))
print('value:', sess.run(input2))

sess.close()

class: <class 'numpy.ndarray'>
value: [0.47037327 0.18372178 0.57085156]


In [30]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [31]:
%tensorboard --logdir Tensorboard_basic_operation_logs --host localhost

Reusing TensorBoard on port 6006 (pid 10720), started 0:00:14 ago. (Use '!kill 10720' to kill it.)